services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5445/verification_db
      - REDIS_URL=redis://redis:6380/0
    depends_on:
      - db
      - redis
  worker:
    build: .
    command: ["python", "-m", "app.workers.callback_worker"]
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5445/verification_db
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=verification_db
    ports:
      - "5445:5445"

  redis:
    image: redis:8-alpine
    ports:
      - "6380:6380"