"""add_is processed column to subscription invoice table

Revision ID: 12d3d3598b91
Revises: e60fb6ed64a7
Create Date: 2026-07-17 13:21:12.168431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d3d3598b91'
down_revision: Union[str, Sequence[str], None] = 'e60fb6ed64a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_invoices', sa.Column('is_processed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_invoices', 'is_processed')
    # ### end Alembic commands ###
