"""add_verification_records

Revision ID: 2b4af3f5ef05
Revises: 95ec55f22fab
Create Date: 2026-07-16 21:01:17.379501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b4af3f5ef05'
down_revision: Union[str, Sequence[str], None] = '95ec55f22fab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('is_successful', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_records_id'), 'verification_records', ['id'], unique=False)
    op.create_index(op.f('ix_verification_records_transaction_id'), 'verification_records', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_records_transaction_id'), table_name='verification_records')
    op.drop_index(op.f('ix_verification_records_id'), table_name='verification_records')
    op.drop_table('verification_records')
    # ### end Alembic commands ###
