"""Add merchant_api_keys table

Revision ID: 459ca9bf98a4
Revises: 7c05b127aeae
Create Date: 2026-07-16 01:41:27.992445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '459ca9bf98a4'
down_revision: Union[str, Sequence[str], None] = '7c05b127aeae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('hashed_secret', sa.String(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_api_keys_client_id'), 'merchant_api_keys', ['client_id'], unique=True)
    op.create_index(op.f('ix_merchant_api_keys_id'), 'merchant_api_keys', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchant_api_keys_id'), table_name='merchant_api_keys')
    op.drop_index(op.f('ix_merchant_api_keys_client_id'), table_name='merchant_api_keys')
    op.drop_table('merchant_api_keys')
    # ### end Alembic commands ###
