"""Add Telegram and Telebirr fields to merchant profile

Revision ID: 59750307c66d
Revises: 12d3d3598b91
Create Date: 2026-07-18 11:43:26.255266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59750307c66d'
down_revision: Union[str, Sequence[str], None] = '12d3d3598b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant_profiles', sa.Column('telegram_id', sa.BigInteger(), nullable=False))
    op.add_column('merchant_profiles', sa.Column('telebirr_name', sa.String(), nullable=False))
    op.add_column('merchant_profiles', sa.Column('telebirr_number', sa.String(), nullable=False))
    op.create_index(op.f('ix_merchant_profiles_telegram_id'), 'merchant_profiles', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchant_profiles_telegram_id'), table_name='merchant_profiles')
    op.drop_column('merchant_profiles', 'telebirr_number')
    op.drop_column('merchant_profiles', 'telebirr_name')
    op.drop_column('merchant_profiles', 'telegram_id')
    # ### end Alembic commands ###
