"""add_partial_unique_tx_index

Revision ID: da5c3198a045
Revises: 747d44182689
Create Date: 2026-07-17 12:42:56.588403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da5c3198a045'
down_revision: Union[str, Sequence[str], None] = '747d44182689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_unique_successful_transaction', 'verification_records', ['transaction_id'], unique=True, postgresql_where=sa.text('is_successful = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_successful_transaction', table_name='verification_records', postgresql_where=sa.text('is_successful = true'))
    # ### end Alembic commands ###
